import {IBlog} from "@/interfaces/blog.ts";

export const BLOG_LIST: IBlog[] = [
    {
        id: 1,
        coverImage: '/images/placeholder.svg',
        name: "Mastering Angular Signals",
        description: "A quick dive into Angular's new reactivity model and how it improves performance.",
        tags: ["Angular", "Signals", "Frontend"],
        content: "",
        createdAt: Date.now() - 86400000 * 5,
        updatedAt: Date.now() - 86400000 * 3,
        readingTimeMins: 5,
        isActive: true,
        isFeatured: true,
    },
    {
        id: 2,
        coverImage: '/images/placeholder.svg',
        name: "Building a Rephrase Extension like Grammarly",
        description: "Step-by-step guide to build a browser extension using OpenAI APIs for rephrasing text.",
        tags: ["Browser Extension", "AI", "OpenAI"],
        content: "",
        createdAt: Date.now() - 86400000 * 10,
        updatedAt: Date.now() - 86400000 * 7,
        isActive: true,
        readingTimeMins: 10,
        isFeatured: false,
    },
    {
        id: 3,
        coverImage: '/images/placeholder.svg',
        name: "Optimizing MongoDB Queries for Large Datasets",
        description: "Techniques to index, aggregate, and optimize queries in production-scale MongoDB setups.",
        tags: ["MongoDB", "Database", "Performance"],
        content: "",
        createdAt: Date.now() - 86400000 * 20,
        updatedAt: Date.now() - 86400000 * 18,
        isActive: true,
        readingTimeMins: 8,
        isFeatured: false,
    },
    {
        id: 4,
        coverImage: '/images/placeholder.svg',
        name: "Deploying React Apps on Vercel Efficiently",
        description: "Best practices and optimizations for hosting modern React apps on Vercel.",
        tags: ["React", "Deployment", "Vercel"],
        content: "",
        createdAt: Date.now() - 86400000 * 15,
        updatedAt: Date.now() - 86400000 * 12,
        isActive: true,
        readingTimeMins: 5,
        isFeatured: true,
    },
    {
        id: 5,
        coverImage: '/images/placeholder.svg',
        name: "Financial Planning for Software Engineers",
        description: "Simple, actionable strategies for managing salary, savings, and investments effectively.",
        tags: ["Finance", "Career", "Personal Growth"],
        content: "",
        createdAt: Date.now() - 86400000 * 25,
        updatedAt: Date.now() - 86400000 * 22,
        isActive: true,
        readingTimeMins: 10,
        isFeatured: false,
    },
];
