import { IProject } from "../interfaces/project";

export const PROJECT_LIST: IProject[] = [
    {
        id: 1,
        name: 'Nexus',
        description: 'My personal portfolio',
        tags: ['Web', 'React', 'Tailwind'],
        isCodeAvailable: true,
        codebaseUrl: 'https://www.github.com/Ayan-Kumar-Saha/nexus',
        isDemoAvailable: true,
        demoUrl: '',
        isFeatured: true,
        imagePath: 'images/placeholder.svg',
        isActive: true
    },
    {
        id: 2,
        name: 'Anuprerna',
        description: 'A ecommerce b2b platform',
        tags: ['Web', 'Angular', 'Spring Boot', 'PostgreSQL'],
        isCodeAvailable: false,
        codebaseUrl: 'https://www.github.com/Ayan-Kumar-Saha/nexus',
        isDemoAvailable: true,
        demoUrl: 'https://anuprerna.com',
        isFeatured: true,
        imagePath: 'images/placeholder.svg',
        isActive: true
    },
    {
        id: 3,
        name: 'Bloomsight',
        description: 'A web analytics tool',
        tags: ['Web', 'Javascript', 'React', 'Typescript'],
        isCodeAvailable: true,
        codebaseUrl: 'https://github.com/bloomscorp/bloomsight.js',
        isDemoAvailable: true,
        demoUrl: 'https://bloomsight.io/',
        isFeatured: true,
        imagePath: 'images/placeholder.svg',
        isActive: true
    },
    {
        id: 4,
        name: 'Scio',
        description: 'A notification based communication app',
        tags: ['Android', 'Web', 'Flutter', 'React', 'Typescript'],
        isCodeAvailable: true,
        codebaseUrl: 'https://github.com/bloomscorp/bloomsight.js',
        isDemoAvailable: true,
        demoUrl: 'https://bloomsight.io/',
        isFeatured: false,
        imagePath: 'images/placeholder.svg',
        isActive: true
    },
    {
        id: 5,
        name: 'ngx-gtag',
        description: 'A notification based communication app',
        tags: ['Web', 'Angular', 'Typescript'],
        isCodeAvailable: true,
        codebaseUrl: 'https://github.com/bloomscorp/bloomsight.js',
        isDemoAvailable: true,
        demoUrl: 'https://bloomsight.io/',
        isFeatured: false,
        imagePath: 'images/placeholder.svg',
        isActive: true
    },
    {
        id: 6,
        name: 'Containova',
        description: 'A notification based communication app',
        tags: ['Android', 'Web', 'Flutter', 'Angular', 'React', 'MongoDB', 'Nodejs'],
        isCodeAvailable: true,
        codebaseUrl: 'https://github.com/bloomscorp/bloomsight.js',
        isDemoAvailable: true,
        demoUrl: 'https://bloomsight.io/',
        isFeatured: false,
        imagePath: 'images/placeholder.svg',
        isActive: true
    },
    {
        id: 7,
        name: 'Tapioca Growth & Partner App',
        description: 'A notification based communication app',
        tags: ['Android', 'Web', 'iOS', 'Apache Cordova', 'Angular', 'MongoDB', 'Nodejs'],
        isCodeAvailable: true,
        codebaseUrl: 'https://github.com/bloomscorp/bloomsight.js',
        isDemoAvailable: true,
        demoUrl: 'https://bloomsight.io/',
        isFeatured: false,
        imagePath: 'images/placeholder.svg',
        isActive: true
    },
    {
        id: 8,
        name: 'Care First App',
        description: 'A notification based communication app',
        tags: ['Android', 'Web', 'iOS', 'Apache Cordova', 'MongoDB', 'Nodejs'],
        isCodeAvailable: true,
        codebaseUrl: 'https://github.com/bloomscorp/bloomsight.js',
        isDemoAvailable: true,
        demoUrl: 'https://bloomsight.io/',
        isFeatured: false,
        imagePath: 'images/placeholder.svg',
        isActive: true
    },
    {
        id: 9,
        name: 'Office Occupancy App',
        description: 'A notification based communication app',
        tags: ['Android', 'Web', 'iOS', 'Apache Cordova', 'MongoDB', 'Nodejs'],
        isCodeAvailable: true,
        codebaseUrl: 'https://github.com/bloomscorp/bloomsight.js',
        isDemoAvailable: true,
        demoUrl: 'https://bloomsight.io/',
        isFeatured: false,
        imagePath: 'images/placeholder.svg',
        isActive: true
    },
    {
        id: 10,
        name: 'AMS Method DB',
        description: 'A notification based communication app',
        tags: ['Web', 'Angular', 'MongoDB', 'Nodejs'],
        isCodeAvailable: false,
        codebaseUrl: '',
        isDemoAvailable: false,
        demoUrl: '',
        isFeatured: false,
        imagePath: 'images/placeholder.svg',
        isActive: true
    }
]