import { IProject } from "../interfaces/project";

export const PROJECT_LIST: IProject[] = [
    {
        id: 1,
        name: 'Nexus',
        description: 'My personal developer portfolio app',
        tags: ['Web', 'React', 'Tailwind'],
        isCodeAvailable: true,
        codebaseUrl: 'https://www.github.com/Ayan-Kumar-Saha/nexus',
        isDemoAvailable: true,
        demoUrl: 'https://ayankumarsaha.dev',
        isFeatured: true,
        imagePath: 'images/projects/nexus.png',
        isActive: true
    },
    {
        id: 2,
        name: 'Anuprerna',
        description: 'A B2B e-commerce platform for wholesale sustainable fabrics',
        tags: ['Web', 'Angular', 'Spring Boot', 'PostgreSQL', 'Tailwind'],
        isCodeAvailable: false,
        codebaseUrl: 'https://www.github.com/Ayan-Kumar-Saha/nexus',
        isDemoAvailable: true,
        demoUrl: 'https://anuprerna.com',
        isFeatured: true,
        imagePath: 'images/projects/anuprerna.png',
        isActive: true
    },
    {
        id: 11,
        name: 'Delta Faucet',
        description: 'A B2C e-commerce platform for faucets, showers, and bathroom accessories',
        tags: ['Web', 'Angular', 'Spring Boot', 'PostgreSQL', 'Tailwind'],
        isCodeAvailable: false,
        codebaseUrl: '',
        isDemoAvailable: true,
        demoUrl: 'https://deltafaucet.in',
        isFeatured: true,
        imagePath: 'images/projects/delta.png',
        isActive: true
    },
    {
        id: 3,
        name: 'Bloomsight',
        description: 'Ultimate website analytics and marketing companion',
        tags: ['Web', 'Javascript', 'React', 'Typescript'],
        isCodeAvailable: true,
        codebaseUrl: 'https://github.com/bloomscorp/bloomsight.js',
        isDemoAvailable: true,
        demoUrl: 'https://bloomsight.io/',
        isFeatured: false,
        imagePath: 'images/projects/bloomsight.png',
        isActive: true
    },
    {
        id: 4,
        name: 'Scio (RPMC)',
        description: 'A push-notification-based communication app for a NAAC-accredited government college',
        tags: ['Android', 'Web', 'Flutter', 'React', 'Typescript'],
        isCodeAvailable: false,
        codebaseUrl: '',
        isDemoAvailable: true,
        demoUrl: 'https://play.google.com/store/apps/details?id=in.org.rpmcollege',
        isFeatured: false,
        imagePath: 'images/projects/scio.png',
        isActive: true
    },
    {
        id: 5,
        name: 'ngx-gtag',
        description: 'An Angular library for integrating with Google Tag Manager (GTM), with SSR support',
        tags: ['Web', 'Angular', 'Typescript'],
        isCodeAvailable: true,
        codebaseUrl: 'https://github.com/bloomscorp/ngx-google-tags-manager',
        isDemoAvailable: true,
        demoUrl: 'https://www.npmjs.com/package/@bloomscorp/ngx-gtag',
        isFeatured: false,
        imagePath: 'images/projects/ngx-gtag.png',
        isActive: true
    },
    {
        id: 6,
        name: 'Containova',
        description: 'An AI-powered application for managing yard containers',
        tags: ['Android', 'iOS', 'Web', 'Flutter', 'Angular', 'React', 'MongoDB', 'Nodejs'],
        isCodeAvailable: false,
        codebaseUrl: '',
        isDemoAvailable: true,
        demoUrl: 'https://containova.com/',
        isFeatured: false,
        imagePath: 'images/projects/containova.png',
        isActive: true
    },
    {
        id: 7,
        name: 'Tapioca Growth App',
        description: 'a cross-platform app for streamlining tapioca farming',
        tags: ['Android', 'Web', 'iOS', 'Apache Cordova', 'Angular', 'MongoDB', 'Nodejs'],
        isCodeAvailable: false,
        codebaseUrl: '',
        isDemoAvailable: true,
        demoUrl: 'https://play.google.com/store/apps/details?id=com.ingredion.tapiocagrowth&hl=en_IN',
        isFeatured: false,
        imagePath: 'images/projects/tapioca-growth.png',
        isActive: true
    },
    {
        id: 8,
        name: 'Care First App',
        description: 'A cross-platform app for monitoring health status',
        tags: ['Android', 'Web', 'iOS', 'Apache Cordova', 'MongoDB', 'Nodejs'],
        isCodeAvailable: false,
        codebaseUrl: '',
        isDemoAvailable: false,
        demoUrl: '',
        isFeatured: false,
        imagePath: 'images/placeholder.svg',
        isActive: true
    },
    {
        id: 9,
        name: 'Office Occupancy App',
        description: 'A cross-platform app for managing office occupancy',
        tags: ['Android', 'Web', 'iOS', 'Apache Cordova', 'MongoDB', 'Nodejs'],
        isCodeAvailable: false,
        codebaseUrl: '',
        isDemoAvailable: false,
        demoUrl: '',
        isFeatured: false,
        imagePath: 'images/placeholder.svg',
        isActive: true
    },
    {
        id: 10,
        name: 'AMS Method DB',
        description: 'An app for storing and managing food processing recipes',
        tags: ['Web', 'Angular', 'MongoDB', 'Nodejs'],
        isCodeAvailable: false,
        codebaseUrl: '',
        isDemoAvailable: false,
        demoUrl: '',
        isFeatured: false,
        imagePath: 'images/placeholder.svg',
        isActive: true
    }
]